{{ if .Values.datacatalogfrontend.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datacatalog-frontend-{{ .Values.global.environment }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: datacatalog
    component: frontend
    env: {{ .Values.global.environment }}
spec:
  destination:
    namespace: {{ .Values.datacatalogfrontend.namespace }}
    name: env-aks-dp-{{ .Values.global.environment }}
  project: {{ .Values.global.environment }}
  source:
    helm:
      values: |-
        appName: datacatalog-frontend-{{ .Values.global.environment }}
        environment: {{ $.Values.global.environment }}

        deployment:
          replicaCount: 1
          image:
            repository: service-dp.westeurope.cloudapp.azure.com/datacatalog-frontend/datacatalog-frontend
            tag: {{ .Values.datacatalogfrontend.helm.values.image.tag | quote }}

          dynamicEnvironment:
            base: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.base }}
            egressBase: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.egressBase }}
            production: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.production }}
            oidcSettings:
              client_id: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.client_id }}
              authority: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.authority }}
              response_type: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.response_type }}
              post_logout_redirect_uri: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.post_logout_redirect_uri }}
              loadUserInfo: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.loadUserInfo }}
              redirect_uri: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.redirect_uri }}
              silent_redirect_uri: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.silent_redirect_uri }}
              automaticSilentRenew: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.automaticSilentRenew }}
              scope: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oidcSettings.scope }}
            oboOidcSettings:
              client_id: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oboOidcSettings.client_id }}
              authority: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oboOidcSettings.authority }}
              response_type: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oboOidcSettings.response_type }}
              popup_redirect_uri: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oboOidcSettings.popup_redirect_uri }}
              scope: {{ .Values.datacatalogfrontend.helm.values.dynamicEnvironment.oboOidcSettings.scope }}

        ingress:
          enabled: true
          host: {{ .Values.datacatalogfrontend.helm.values.ingress.host }}
          path: {{ .Values.datacatalogfrontend.helm.values.ingress.path }}

          annotations:
            # nginx.ingress.kubernetes.io/rewrite-target: /$2
            # cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
          {{- range $key, $value := .Values.global.ingress.annotations }}
            {{ $key }}: {{ $value | quote }}
          {{- end }}

          {{- if .Values.datacatalogfrontend.helm.values.ingress.tls }}
          tls:
            hosts:
          {{- range .Values.datacatalogfrontend.helm.values.ingress.tls.hosts }}
            - secretName: {{ .secretName }}
              hosts:
          {{ .hosts | toYaml | indent 4 }}
          {{- end }}
          {{- end }}

        externalSecret:
          enabled: {{ .Values.datacatalogfrontend.helm.values.externalSecret.enabled }}

          role: {{ .Values.datacatalogfrontend.helm.values.externalSecret.role | quote }}

          secrets:
{{ .Values.datacatalogfrontend.helm.values.externalSecret.secrets | toYaml | indent 12 }}

    path: {{ default .Values.global.path .Values.datacatalogfrontend.path }}
    repoURL: {{ .Values.datacatalogfrontend.repoURL }}
    targetRevision: {{ default .Values.global.targetRevision .Values.datacatalogfrontend.targetRevision }}
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
    - CreateNamespace=true
{{ end }}
