{{ if .Values.flink.enabled}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-{{ .Values.global.environment }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: flink
    env: {{ .Values.global.environment }}
spec:
  destination:
    namespace: {{ .Values.flink.namespace }}
    name: env-aks-dp-{{ .Values.global.environment }}
  project: {{ .Values.global.environment }}
  source:
    helm:
      values: |-
        image: {{ .Values.flink.image.repo }}
        imageTag: {{ .Values.flink.image.tag }}
        imagePullPolicy: Always
        
        nodeSelector:
          agentpool: tooling

        ingress:
          enabled: {{ .Values.flink.ingress.enabled }}
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
          host: dp-test.westeurope.cloudapp.azure.com
          path: /flink(/|$)(.*)

        flink:
          jobmanager_heap_mb: 1024
          taskmanager_heap_mb: 1024
          num_taskmanagers: 1
          num_slots_per_taskmanager: 1

          ## Other config options for flink-conf.yaml
          #config: |
          #  some.option: 3

    path: {{ default .Values.global.path .Values.flink.path }}
    repoURL: {{ .Values.flink.repoURL }}
    targetRevision: {{ default .Values.global.targetRevision .Values.flink.targetRevision }}
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
    - CreateNamespace=true
{{ end }}
  