apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osiris-ingress-api-{{ .Values.global.environment }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: osiris
    component: ingress
    env: {{ .Values.global.environment }}
spec:
  destination:
    namespace: {{ .Values.osirisingress.namespace }}
    name: env-aks-dp-{{ .Values.global.environment }}
  project: {{ .Values.global.environment }}
  source:
    helm:
      values: |-
        appName: {{ .Values.osirisingress.appName }}-{{ .Values.global.environment }}
        deployment:
          replicas: 1
          nodeSelector:
            agentpool: worker
          image:
            repository: service-dp.westeurope.cloudapp.azure.com/osiris-ingress-api/osiris-ingress-api
            tag: {{ .Values.osirisingress.helm.values.image.tag | quote }}

        ingress:
          enabled: true
          host: dp-{{ .Values.global.environment }}.westeurope.cloudapp.azure.com
          path: /osiris-ingress(/|$)(.*)
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
          {{- range $key, $value := .Values.global.ingress.annotations }}
            {{ $key }}: {{ $value | quote }}
          {{- end }}

        config:
          conf.ini: |
            [Logging]
            configuration_file = /etc/osiris/log.conf

            [FastAPI]
            root_path = /osiris-ingress

            [Azure Storage]
            account_url = https://dpcontentstorage{{ .Values.global.environment }}.dfs.core.windows.net/
            filesystem_name = datasets
    path: {{ default .Values.global.path .Values.osirisingress.path }}
    repoURL: {{ .Values.osirisingress.repoURL }}
    targetRevision: {{ default .Values.global.targetRevision .Values.osirisingress.targetRevision }}
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
    - CreateNamespace=true
